### ISSUE TITLE
Not clear how to trigger restock/pick actions

### ISSUE THREAD

**Issue by TheGoldenMallet** [theliamcrawford/Warehouse---CS_2820#12]
When robots reach the pick station or receiving dock, there needs to be a way to detect this event and trigger a pick/restock action. I'm unsure if this should be handled through RobotScheduler or if RobotScheduler should notify another class somehow.

**Comment by theliamcrawford** [comment]
Here's my understanding, and correct me if I'm wrong: 

- the robots are the only ones that know their positions (besides the observing visualizer).
- RS knows where the pickers and receiving docks are

My solution: give RS four new, simple functions that the master can call before ticking it:

1. public Boolean robotsAtPicker() - returns 1 if any robot is at the picking station
2. public Boolean robotsAtRestock() - returns 1 if any robot is at the restock station
3. public ArrayList<Shelf> shelvesAtPicker() - returns an ArrayList of shelves that are at picking stations
4. public ArrayList<Shelf> shelvesAtRestock() - returns an ArrrayList of shelves that are at Restock

3. and 4. are only called if 1 and 2 are called respectively. Master will hand the appropriate instructions off to inventory and OrderSystem. The reason I'm thinking they should return ArrayLists is for future iterations where there may be multiple picking stations.

**Comment by TheGoldenMallet** [comment]
Implemented robotsAtPicker, robotsAtRestock, shelvesAtPicker, shelvesAtRestock. Now the rest just needs to be handled on the master's end.
