### ISSUE TITLE
RobotScheduler variable "shelvesForOrder" rewrites when given another order

### ISSUE THREAD

**Issue by theliamcrawford** [theliamcrawford/Warehouse---CS_2820#9]
As of right now, there is not a way to queue **orders** in the Robot Scheduler. This scenario can happen as of now.

Master hands a HashSet to the RobotScheduler before it completes assigning the current set of shelves. 

Possible solution: create a queue for the orders and deal with one hashset at a time

**Comment by TheGoldenMallet** [comment]
Created PriorityQueue<HashSet<Shelf>> pendingOrders
